#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:05:00

#parse config.json for input parameters
out1=$(jq -r .n_surfs config.json)
out2=$(jq -r .output config.json)
out3=$(jq -r .smoothing config.json)

export SUBJECTS_DIR=$(dirname "$out2")
export FREESURFER_LICENSE=/usr/local/freesurfer/license.txt

time singularity exec --writable -e docker://brainlife/freesurfer:6.0.0 bash -c "echo $FREESURFER_LICENSE > /usr/local/freesurfer/license.txt && ./generate_equivolumetric_surfaces.py "$out1" "$out2" "$out3""
